export const INCREMENT_USER_ID = 'INCREMENT_USER_ID'
export const INCREMENT_GROUP_ID = 'INCREMENT_GROUP_ID'

export const HANDLE_CHANGE_SEARCH_ID = 'HANDLE_CHANGE_SEARCH_ID'

export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID'
export const GET_MOVIE_FROM_TMDB = 'GET_MOVIE_FROM_TMDB'

export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIES_BY_USER_ID = 'GET_MOVIES_BY_USER_ID'
